server:
  port: 9090


mybatis:
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.sid.model  # 注意：对应实体类的路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制台打印sql


#pagehelper分页插件
pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#public-key:

# Spring Datasource Settings
spring:
  datasource: #数据库相关
    url: jdbc:oracle:thin:@127.0.0.1:1521:ORCL
    username: loan
    password: abc
    driver-class-name: oracle.jdbc.driver.OracleDriver
    #dataSource类型
    type: com.alibaba.druid.pool.DruidDataSource
    #    2.0之后新特性 不加就不会自动建表
    #initialization-mode: always

    #druid配置
    druid:
      initial-size: 5  #初始化连接数
      max-active: 20 #最大连接数
      min-idle: 5 #最小连接数
      max-wait: 6000 #最大等待时间
#      connect-properties: config.decrypt=true;config.decrypt.key=
      #开启Web监控
      web-stat:
        enabled: true
      #开启AOP监控
      aop-stat:
        enabled: true
      #开启WallFilter
      wall:
        enabled: true
        throw-exception: true
      config:
        enabled: true
        key:
#showSql
logging:
  config: classpath:log4j2-test.xml
  level:
    com:
      em: debug

sb:
  exportFilePath: /Users/wangnz/Documents/export/
  encryptFilePath: /Users/wangnz/Documents/export/
  companyName: abc
  rsaPubKey: "/Users/wangnz/Documents/rsa_public_key.pem"
  url: https://www.baidu.com
  pageSize: 5
  #写入filesize页就换一个文件继续写入。
  fileSize: 100
